/* =========================================================
   easyHMS – Rollback: LookupMaster (CHIEF_COMPLAINT)
   Deletes ONLY seeded CC codes and ONLY if NOT referenced.
   ========================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
BEGIN TRAN;

-- The exact codes we seeded
DECLARE @Codes TABLE(Code nvarchar(100) PRIMARY KEY);
INSERT INTO @Codes(Code)
VALUES
 (N'GEN-FEVER'),(N'GEN-HEADACHE'),(N'GEN-FATIGUE'),(N'GEN-MYALGIA'),
 (N'GEN-COUGH'),(N'GEN-SORETHROAT'),(N'GEN-CORYZA'),(N'GEN-ABDOMINAL-PAIN'),
 (N'GEN-DIARRHEA'),(N'GEN-VOMITING'),(N'GEN-ANOREXIA'),(N'GEN-DIZZINESS'),

 (N'IM-CHEST-PAIN'),(N'IM-DYSPNEA'),(N'IM-PALPITATIONS'),(N'IM-EDEMA'),
 (N'IM-SYNCOPE'),(N'IM-WEIGHT-LOSS'),(N'IM-NIGHT-SWEATS'),(N'IM-JAUNDICE'),
 (N'IM-HEMOPTYSIS'),(N'IM-POLYURIA'),

 (N'PED-FEVER'),(N'PED-POOR-FEEDING'),(N'PED-IRRITABILITY'),(N'PED-WHEEZE'),
 (N'PED-RASH'),(N'PED-SEIZURE'),(N'PED-GE'),(N'PED-OTALGIA'),
 (N'PED-SORETHROAT'),(N'PED-DEV-DELAY'),

 (N'OBG-AMENORRHEA'),(N'OBG-IRREGULAR-MC'),(N'OBG-DYSMENORRHEA'),(N'OBG-MENORRHAGIA'),
 (N'OBG-DISCHARGE'),(N'OBG-LAP'),(N'OBG-INFERTILITY'),(N'OBG-NVP'),
 (N'OBG-DFM'),(N'OBG-BREAST'),

 (N'SURG-ABDOMINAL-PAIN'),(N'SURG-LUMP'),(N'SURG-HERNIA'),(N'SURG-RECTAL-BLEED'),
 (N'SURG-ULCER'),(N'SURG-ABSCESS'),(N'SURG-BILIARY-COLIC'),(N'SURG-APPENDICITIS'),
 (N'SURG-VARICOSE'),(N'SURG-TRAUMA'),

 (N'ORTHO-BACK-PAIN'),(N'ORTHO-NECK-PAIN'),(N'ORTHO-KNEE-PAIN'),(N'ORTHO-SHOULDER-PAIN'),
 (N'ORTHO-STIFFNESS'),(N'ORTHO-SWELLING'),(N'ORTHO-FRACTURE'),(N'ORTHO-GAIT'),
 (N'ORTHO-SCIATICA'),(N'ORTHO-OSTEOPOROSIS'),

 (N'CARD-ANGINA'),(N'CARD-DOE'),(N'CARD-ORTHOPNEA'),(N'CARD-PND'),
 (N'CARD-PALP'),(N'CARD-SYNCOPE'),(N'CARD-EDEMA'),(N'CARD-CLAUDICATION'),
 (N'CARD-CYANOSIS'),(N'CARD-FATIGUE'),

 (N'NEURO-HEADACHE'),(N'NEURO-SEIZURE'),(N'NEURO-WEAKNESS'),(N'NEURO-PARESTHESIA'),
 (N'NEURO-VERTIGO'),(N'NEURO-DYARTHRIA'),(N'NEURO-MEMORY'),(N'NEURO-GAIT'),
 (N'NEURO-FACIAL'),(N'NEURO-VISUAL'),

 (N'URO-DYSURIA'),(N'URO-FREQUENCY'),(N'URO-HEMATURIA'),(N'URO-RENAL-COLIC'),
 (N'URO-RETENTION'),(N'URO-INCONTINENCE'),(N'URO-STREAM'),(N'URO-SUPRAPUBIC'),
 (N'URO-TESTICULAR'),(N'URO-RUTI'),

 (N'DERM-PRURITUS'),(N'DERM-RASH'),(N'DERM-ACNE'),(N'DERM-ALOPECIA'),
 (N'DERM-PIGMENT'),(N'DERM-XEROSIS'),(N'DERM-SCALING'),(N'DERM-BLISTERS'),
 (N'DERM-NAILS'),(N'DERM-URTICARIA'),(N'DERM-TINEA'),

 (N'ENT-OTALGIA'),(N'ENT-HL'),(N'ENT-TINNITUS'),(N'ENT-OTORRHEA'),
 (N'ENT-PHARYNGITIS'),(N'ENT-DYSPHONIA'),(N'ENT-NASAL-OBSTR'),(N'ENT-EPISTAXIS'),
 (N'ENT-ALLERGIC'),(N'ENT-VERTIGO'),(N'ENT-FOREIGN-BODY'),

 (N'OPH-BLURRED'),(N'OPH-PAIN'),(N'OPH-RED'),(N'OPH-EPIPHORA'),
 (N'OPH-DIPLOPIA'),(N'OPH-PHOTOPHOBIA'),(N'OPH-FB'),(N'OPH-FLOATERS'),
 (N'OPH-LOV'),(N'OPH-ALLERGY'),

 (N'PSY-ANXIETY'),(N'PSY-DEPRESSION'),(N'PSY-SUICIDAL'),(N'PSY-INSOMNIA'),
 (N'PSY-AGGRESSION'),(N'PSY-HALLUCINATIONS'),(N'PSY-DELUSIONS'),(N'PSY-OCD'),
 (N'PSY-SUBSTANCE'),(N'PSY-MEMORY');

-- Candidates (LookupTypeId=1 + our codes)
;WITH candidates AS (
  SELECT lm.LookupId, lm.Code
  FROM dbo.LookupMaster lm
  JOIN @Codes c ON c.Code = ISNULL(lm.Code,N'')
  WHERE lm.LookupTypeId = 1
),
-- Check references: LookupPersonal.MasterLookupId (and any other table if you later add FK to LookupMaster)
refs AS (
  SELECT DISTINCT lp.MasterLookupId AS LookupId
  FROM dbo.LookupPersonal lp
  WHERE lp.MasterLookupId IS NOT NULL
)
DELETE lm
FROM dbo.LookupMaster lm
JOIN candidates cand ON cand.LookupId = lm.LookupId
LEFT JOIN refs r ON r.LookupId = lm.LookupId
WHERE r.LookupId IS NULL;  -- delete only if not referenced

COMMIT;
PRINT N'Chief Complaint rollback completed (non-referenced rows removed).';
END TRY
BEGIN CATCH
  IF XACT_STATE() <> 0 ROLLBACK;
  THROW;
END CATCH;
